config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :kategoris
  devise_for :authors
  root "blog/posts#index"
  
  namespace :authors do
     get '/account' => 'accounts#edit', as: :account
     put '/info' => 'accounts#update_info', as: :info 
     put '/change_password' => 'accounts#change_password', as: :change_password
     resources :posts do
         put 'publish' => 'posts#publish', on: :member
         put 'unpublish' => 'posts#unpublish', on: :member
     end
  end

  scope module: 'blog' do 
       get 'hakkimda' => 'pages#hakkimda', as: :hakkimda
       get 'iletisim' => 'pages#iletisim', as: :iletisim
       get 'posts' => 'posts#index', as: :posts
       get 'posts/:id' => 'posts#show', as: :post
  end
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts
  
  validates_presence_of :name, on: :update, :message => 'İsim alanı gerekli.'
  
  def change_password(attrs)
      update(password: attrs[:new_password], password_configuration: attrs[:new_password_confirmation])
  end
  
  def gravatar_image_url
      "https://www.gravatar.com/avatar/#{gravatar_hash}"
  end
  
  def gravatar_hash
      Digest::MD5.hexdigest(email.downcase)
  end
  
  def display_name
      if name.present?
          name
      else
          "Üye"
      end
  end
end

app/controllers/author/posts_controller.rb
module Author
    class PostsController < AuthorController
      before_action :set_post, only: [:show, :edit, :update, :destroy]
    
      # GET /posts
      # GET /posts.json
      def index
        @posts = Post.most_recent
      end
    
      # GET /posts/1
      # GET /posts/1.json
      def show
      end
    
      # GET /posts/new
      def new
        @post = Post.new
      end
    
      # GET /posts/1/edit
      def edit
      end
    
      # POST /posts
      # POST /posts.json
      def create
        @post = Post.new(post_params)
    
        respond_to do |format|
          if @post.save
            format.html { redirect_to @post, notice: 'Post was successfully created.' }
            format.json { render :show, status: :created, location: @post }
          else
            format.html { render :new }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # PATCH/PUT /posts/1
      # PATCH/PUT /posts/1.json
      def update
        respond_to do |format|
          if @post.update(post_params)
            format.html { redirect_to @post, notice: 'Post was successfully updated.' }
            format.json { render :show, status: :ok, location: @post }
          else
            format.html { render :edit }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # DELETE /posts/1
      # DELETE /posts/1.json
      def destroy
        @post.destroy
        respond_to do |format|
          format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
    
      private
        # Use callbacks to share common setup or constraints between actions.
        def set_post
          @post = Post.friendly.find(params[:id])
        end
    
        # Never trust parameters from the scary internet, only allow the white list through.
        def post_params
          params.require(:post).permit(:kategoriId, :baslik, :aciklama, :icerik, :foto, :tarih, :okunma)
        end
    end
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
    before_action :authenticate_author!
end

app/controllers/authors/accounts_controller.rb
module Authors
    class AccountsController < AuthorController

        def update_info
            # email must be formatted correctly
            # name is required on update
            if current_author.update(author_info_params)
                 flash[:success] = 'Bilgileriniz güncellendi.'
            else
                flash[:danger] = '! Lütfen tekrar deneyiniz.'
            end
            redirect_to authors_account_path
        end
        
        def edit
            
        end
        
        def change_password
            author = current_author
            if author.valid_password?(author_password_params[:current_password])
                if author.change_password(author_password_params)
                sign_in(author, bypass: true)
                 flash[:success] = 'Şifre başarıyla değiştirildi.'
                else
                 flash[:danger] =  '! Lütfen tekrar deneyiniz.'
                end
            else
                flash[:danger] ='Mevcut şifre hatalı.'
            end
            redirect_to authors_account_path
        end
        
        private
        
        def author_info_params
            params.require(:author).permit(:name, :email, :bio)
        end
        
        def author_password_params
            params.require(:author).permit(:currnet_password, :new_password, :new_password_confirmation)
        end
    end
end

app/controllers/authors/posts_controller.rb
module Authors
    class PostsController < AuthorController
      before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]
    
      # GET /posts
      # GET /posts.json
      def index
        @posts = current_author.posts.most_recent
      end
    
      # GET /posts/1
      # GET /posts/1.json
      def show
      end
    
      # GET /posts/new
      def new
        @post = current_author.posts.new
      end
    
      # GET /posts/1/edit
      def edit
      end
      
      def publish
          @post.publish
          redirect_to authors_posts_url
      end
      
      def unpublish
          @post.unpublish
          redirect_to authors_posts_url
      end
  
    
      # POST /posts
      # POST /posts.json
      def create
        @post = current_author.posts.new(post_params)
    
        respond_to do |format|
          if @post.save
            format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
            format.json { render :show, status: :created, location: @post }
          else
            format.html { render :new }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # PATCH/PUT /posts/1
      # PATCH/PUT /posts/1.json
      def update
        respond_to do |format|
          if @post.update(post_params)
            format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
            format.json { render :show, status: :ok, location: @post }
          else
            format.html { render :edit }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # DELETE /posts/1
      # DELETE /posts/1.json
      def destroy
        @post.destroy
        respond_to do |format|
          format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
    
      private
        # Use callbacks to share common setup or constraints between actions.
        def set_post
          @post = current_author.posts.friendly.find(params[:id])
        end
    
        # Never trust parameters from the scary internet, only allow the white list through.
        def post_params
          params.require(:post).permit(:baslik, :aciklama, :icerik, :tag_list, :resim)
        end
    end
end

app/views/authors/accounts/edit.html.erb
<div class="row">
  <div class="col-md-6"> 
    <%= form_tag authors_info_path, method: :put do %>
        <%= fields_for :author do |f| %>
        <div class="card">
        <div class="card-block" style="padding:10px">
            <div class="card-title">
                Temel Bilgiler
            </div>
        </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <%= image_tag(current_author.gravatar_image_url) %>
            </li>
            <li class="list-group-item">
                 <div class="field">
                    <%= f.label :'İsim' %><br>
                    <%= f.text_field :name, value:current_author.name, class:'form-control' %>
                  </div>
            </li>
            <li class="list-group-item">
              <div class="field">
                <%= f.label :Email %><br>
                <%= f.text_field :email, value:current_author.email, class:'form-control' %>
              </div>
            </li>
            <li class="list-group-item">
                   <div class="field">
                    <%= f.label :Biografi %><br>
                    <%= f.text_area :bio, value:current_author.bio, class:'form-control' %>
                  </div>
            </li>
            <li class="list-group-item">
                <%= f.submit "Bilgileri Güncelle", class: 'btn btn-primary' %>
            </li>
          </ul>
        </div>
        <% end %>
    <% end %>
     </div> 

    <div class="col-md-6">
      <%= form_tag authors_change_password_path, method: :put do %>
      <%= fields_for :author do |f| %>
        <div class="card">
        <div class="card-block" style="padding:10px">
            <div class="card-title">
                Şifreyi değiştir
            </div>
        </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
                 <div class="field">
                    <%= f.label :'Şimdiki Şifre' %><br>
                    <%= f.password_field :current_password, class:'form-control' %>
                  </div>
            </li>
            <li class="list-group-item">
              <div class="field">
                <%= f.label :'Yeni Şifre' %><br>
                <%= f.password_field :new_password, class:'form-control' %>
              </div>
            </li>
            <li class="list-group-item">
                   <div class="field">
                    <%= f.label :'Şifreyi Doğrular' %><br>
                    <%= f.password_field :new_password_confirmation, class:'form-control' %>
                  </div>
            </li>
            <li class="list-group-item">
                <%= f.submit "Şifreyi Güncelle", class: 'btn btn-warning' %>
            </li>
          </ul>
        </div>
         <% end %>
         <% end %>
    </div>

</div>