config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :kategoris
  devise_for :authors
  root "blog/posts#index"
  
  namespace :authors do
     get '/account' => 'accounts#edit', as: :account
     put '/info' => 'accounts#update_info', as: :info 
     put '/change_password' => 'accounts#change_password', as: :change_password
     resources :posts do
         put 'publish' => 'posts#publish', on: :member
         put 'unpublish' => 'posts#unpublish', on: :member
     end
  end

  scope module: 'blog' do 
       get 'hakkimda' => 'pages#hakkimda', as: :hakkimda
       get 'iletisim' => 'pages#iletisim', as: :iletisim
       get 'posts' => 'posts#index', as: :posts
       get 'posts/:id' => 'posts#show', as: :post
  end
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts
  
  validates_presence_of :name, on: :update, :message => 'İsim alanı gerekli.'
  
  def change_password(attrs)
      update(password: attrs[:new_password], password_configuration: attrs[:new_password_confirmation])
  end
  
  def gravatar_image_url
      "https://www.gravatar.com/avatar/#{gravatar_hash}"
  end
  
  def gravatar_hash
      Digest::MD5.hexdigest(email.downcase)
  end
  
  def display_name
      if name.present?
          name
      else
          "Üye"
      end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id                :integer          not null, primary key
#  kategoriId        :integer
#  baslik            :string
#  aciklama          :text
#  icerik            :text
#  foto              :string
#  tarih             :datetime
#  okunma            :integer
#  slug              :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  author_id         :integer
#  yayinlanma        :boolean          default(FALSE)
#  yayinlanma_tarihi :datetime
#

class Post < ApplicationRecord
    
    has_attached_file :resim, styles: { medium: "670x402>", thumb: "360x216>" }, default_url:
"/images/:style/missing.png"
validates_attachment_content_type :resim, content_type: /\Aimage\/.*\z/
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  extend FriendlyId
  friendly_id :baslik, use: :slugged
  
  belongs_to :author, :optional => true
  
  PER_PAGE = 6
  
  scope :most_recent, -> {order(yayinlanma_tarihi: :desc)}
  scope :yayinlanma, -> {where(yayinlanma: :true)}
  scope :recent_paginated, -> (page) { most_recent.paginate(page: page, per_page: PER_PAGE) }
  scope :with_tag, -> (tag) {  tagged_with(tag) if tag.present? }

  
  scope :list_for, -> (page, tag) do
           recent_paginated(page).with_tag(tag)
  end
  
  
  def should_generate_new_friendly_id?
	baslik_changed?
  end

 def display_day_published
    if yayinlanma_tarihi.present?
	    "Yayınlanma: #{yayinlanma_tarihi.strftime('%-b %-d, %Y')}"
	else
	    "Henüz yayınlanmadı."
	end
  end
  
  def publish
      update(yayinlanma: true,yayinlanma_tarihi: Time.now)
  end
  def unpublish
      update(yayinlanma: false,yayinlanma_tarihi: nil)
  end
end

app/controllers/author/posts_controller.rb
module Author
    class PostsController < AuthorController
      before_action :set_post, only: [:show, :edit, :update, :destroy]
    
      # GET /posts
      # GET /posts.json
      def index
        @posts = Post.most_recent
      end
    
      # GET /posts/1
      # GET /posts/1.json
      def show
      end
    
      # GET /posts/new
      def new
        @post = Post.new
      end
    
      # GET /posts/1/edit
      def edit
      end
    
      # POST /posts
      # POST /posts.json
      def create
        @post = Post.new(post_params)
    
        respond_to do |format|
          if @post.save
            format.html { redirect_to @post, notice: 'Post was successfully created.' }
            format.json { render :show, status: :created, location: @post }
          else
            format.html { render :new }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # PATCH/PUT /posts/1
      # PATCH/PUT /posts/1.json
      def update
        respond_to do |format|
          if @post.update(post_params)
            format.html { redirect_to @post, notice: 'Post was successfully updated.' }
            format.json { render :show, status: :ok, location: @post }
          else
            format.html { render :edit }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # DELETE /posts/1
      # DELETE /posts/1.json
      def destroy
        @post.destroy
        respond_to do |format|
          format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
    
      private
        # Use callbacks to share common setup or constraints between actions.
        def set_post
          @post = Post.friendly.find(params[:id])
        end
    
        # Never trust parameters from the scary internet, only allow the white list through.
        def post_params
          params.require(:post).permit(:kategoriId, :baslik, :aciklama, :icerik, :foto, :tarih, :okunma)
        end
    end
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
    before_action :authenticate_author!
end

app/controllers/authors/accounts_controller.rb
module Authors
    class AccountsController < AuthorController

        def update_info
            # email must be formatted correctly
            # name is required on update
            if current_author.update(author_info_params)
                 flash[:success] = 'Bilgileriniz güncellendi.'
            else
                flash[:danger] = '! Lütfen tekrar deneyiniz.'
            end
            redirect_to authors_account_path
        end
        
        def edit
            
        end
        
        def change_password
            author = current_author
            if author.valid_password?(author_password_params[:current_password])
                if author.change_password(author_password_params)
                sign_in(author, bypass: true)
                 flash[:success] = 'Şifre başarıyla değiştirildi.'
                else
                 flash[:danger] =  '! Lütfen tekrar deneyiniz.'
                end
            else
                flash[:danger] ='Mevcut şifre hatalı.'
            end
            redirect_to authors_account_path
        end
        
        private
        
        def author_info_params
            params.require(:author).permit(:name, :email, :bio)
        end
        
        def author_password_params
            params.require(:author).permit(:currnet_password, :new_password, :new_password_confirmation)
        end
    end
end

app/controllers/authors/posts_controller.rb
module Authors
    class PostsController < AuthorController
      before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]
    
      # GET /posts
      # GET /posts.json
      def index
        @posts = current_author.posts.most_recent
      end
    
      # GET /posts/1
      # GET /posts/1.json
      def show
      end
    
      # GET /posts/new
      def new
        @post = current_author.posts.new
      end
    
      # GET /posts/1/edit
      def edit
      end
      
      def publish
          @post.publish
          redirect_to authors_posts_url
      end
      
      def unpublish
          @post.unpublish
          redirect_to authors_posts_url
      end
  
    
      # POST /posts
      # POST /posts.json
      def create
        @post = current_author.posts.new(post_params)
    
        respond_to do |format|
          if @post.save
            format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
            format.json { render :show, status: :created, location: @post }
          else
            format.html { render :new }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # PATCH/PUT /posts/1
      # PATCH/PUT /posts/1.json
      def update
        respond_to do |format|
          if @post.update(post_params)
            format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
            format.json { render :show, status: :ok, location: @post }
          else
            format.html { render :edit }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # DELETE /posts/1
      # DELETE /posts/1.json
      def destroy
        @post.destroy
        respond_to do |format|
          format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
    
      private
        # Use callbacks to share common setup or constraints between actions.
        def set_post
          @post = current_author.posts.friendly.find(params[:id])
        end
    
        # Never trust parameters from the scary internet, only allow the white list through.
        def post_params
          params.require(:post).permit(:baslik, :aciklama, :icerik, :tag_list, :resim)
        end
    end
end

app/controllers/blog/posts_controller.rb
module Blog
    class PostsController < BlogController

      # GET /posts
      # GET /posts.json
      def index
       @posts = stroage.list_for(params[:page], params[:tag])
      end
    
      # GET /posts/1
      # GET /posts/1.json
      def show
             @post = stroage.friendly.find(params[:id])
      end
      
        
    before_action :set_locale
    def set_locale
      I18n.locale=params[:locale]||I18n.default_locale
    end
    
      private
      
      def stroage
          Post.yayinlanma
      end
    
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.erb
 <div class="container">
 <%= form_with(model: post, url: url, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<p></p>
<div style="margin-top:20px">
<div class="row">
    <div class="col-md-4">
        <div class="card">
          <div class="card-body">
              
              <% if @post.new_record? %>
                <h5 class="card-title"><%= t('yeniyazi') %></h5>
              <% else %>
              <h5 class="card-title">
                  <b>Düzenle</b>
                  <span class="thin-text"> <%= @post.baslik %></span>
              </h5>

              <% end %>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="field">
                <%= form.label t('baslik') %>
                <%= form.text_field :baslik, class:'form-control' %>
              </div>
            </li>
            <li class="list-group-item">
                   <div class="field">
                    <%= form.label t('aciklama') %><br>
                    <%= form.text_area :aciklama, class:'form-control' %>
                  </div>
            </li>
             <li class="list-group-item">
                   <div class="field">
                    <%= form.label t('etiketler') %><br>
                    <%= form.text_area :tag_list, class:'form-control' %>
                  </div>
            </li>
             <li class="list-group-item">
                 <div class="field">
                <%= form.label t('resim') %><br>
                <%= form.file_field :resim,  class:'form-control' %>
              </div>
            </li>

            <li class="list-group-item">
                    <div class="actions">
                    <%= form.submit t('kaydet'), class:'btn btn-success btn-block' %>
                  </div>
            </li>
          </ul>
        </div>

    </div>
    
    <div class="col-md-8">
          <div class="field">
    <%= form.text_area :icerik %>
  </div>
    </div>
</div>
</div>
<% end %>
</div>

app/views/authors/posts/_post.html.erb
<tr>
  
    <td> <%= link_to post.baslik, authors_post_path(post) %> </td>
    <td> </td>
    <% if post.yayinlanma? %>
        <td> <%= link_to 'Yayinda değil', unpublish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-primary' %> </td>
    <% else %>
        <td> <%= link_to 'Yayında', publish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-success' %> </td>
    <% end %>
    
     <td> <%= link_to 'Düzenle', edit_authors_post_path(post), class: 'btn btn-sm btn-warning' %> </td>
      <td> <%= link_to 'Sil', authors_post_path(post), method: :delete, data:{confirm: 'Silmek istediğinize emin misiniz?'}, class: 'btn btn-sm btn-danger' %> </td>
</tr>

app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Düzenle #{@post.baslik}") %>
<% provide(:author, 'active') %>

<%= render 'form', post: @post, url: authors_post_url(@post)  %>

app/views/authors/posts/index.html.erb
<% provide(:page_title, 'Tüm Yazılar') %>
<% provide(:author, 'active') %>
<div class="container">
<div class="row">
    <p></p>
    <p></p>
    <div style="margin-top:20px">
    <%= link_to t('yeniyazi'), new_authors_post_path, class: 'btn btn-primary btn-lg' %>
    </div>  
    <table class="table table-striped" style="margin-top:10px">
        <tr>
            <td colspan="5"><%=  t('baslik') %></td>
        </tr>
        <%= render @posts %>
    </table>
</div></div>

app/views/authors/posts/new.html.erb
<% provide(:page_title, 'Yeni Yazı') %>
<% provide(:author, 'active') %>
<div class="container">
<%= render 'form', post: @post, url: authors_posts_url  %>

<%= link_to 'Geri dön', authors_posts_path %>
</div>

app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.baslik) %>
<% provide(:author, 'active') %>



<div class="container">
    
	<div class="row">
	  
					<!-- Post content -->
					<div class="col-md-8">
	<p><p></p></p>				    
					      <div>
    <%= link_to 'Düzenle', edit_authors_post_path(@post), class: 'btn btn-sm btn-warning' %>
    <%= link_to 'Sil', authors_post_path(@post), method: :delete, data:{confirm: 'Silmek istediğinize emin misiniz?'}, class: 'btn btn-sm btn-danger' %>
</div>
<br><p></p>
						<div class="section-row sticky-container">
							<div class="main-post">
								<h3>  <%= @post.baslik %></h3>
								<p> <%= @post.icerik.html_safe %></p>
							
						</div>

						<!-- ad -->
					
						<!-- ad -->
						
						<!-- author -->
					
						<!-- /author -->

						<!-- comments -->
						
						<!-- /comments -->

						<!-- reply -->
					
						<!-- /reply -->
					</div>
					<!-- /Post content -->

					<!-- aside -->
					
					<!-- /aside -->
				</div>

</div>