config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :kategoris
  devise_for :authors
  root "blog/posts#index"
  
  namespace :authors do
     get '/account' => 'accounts#edit', as: :account
     put '/info' => 'accounts#update_info', as: :info 
     put '/change_password' => 'accounts#change_password', as: :change_password
     resources :posts do
         put 'publish' => 'posts#publish', on: :member
         put 'unpublish' => 'posts#unpublish', on: :member
     end
  end

  scope module: 'blog' do 
       get 'hakkimda' => 'pages#hakkimda', as: :hakkimda
       get 'iletisim' => 'pages#iletisim', as: :iletisim
       get 'posts' => 'posts#index', as: :posts
       get 'posts/:id' => 'posts#show', as: :post
  end
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/kategori.rb
class Kategori < ApplicationRecord
end

app/controllers/kategoris_controller.rb
class KategorisController < ApplicationController
  before_action :set_kategori, only: [:show, :edit, :update, :destroy]

  # GET /kategoris
  # GET /kategoris.json
  def index
    @kategoris = Kategori.all
  end

  # GET /kategoris/1
  # GET /kategoris/1.json
  def show
  end

  # GET /kategoris/new
  def new
    @kategori = Kategori.new
  end

  # GET /kategoris/1/edit
  def edit
  end

  # POST /kategoris
  # POST /kategoris.json
  def create
    @kategori = Kategori.new(kategori_params)

    respond_to do |format|
      if @kategori.save
        format.html { redirect_to @kategori, notice: 'Kategori was successfully created.' }
        format.json { render :show, status: :created, location: @kategori }
      else
        format.html { render :new }
        format.json { render json: @kategori.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kategoris/1
  # PATCH/PUT /kategoris/1.json
  def update
    respond_to do |format|
      if @kategori.update(kategori_params)
        format.html { redirect_to @kategori, notice: 'Kategori was successfully updated.' }
        format.json { render :show, status: :ok, location: @kategori }
      else
        format.html { render :edit }
        format.json { render json: @kategori.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kategoris/1
  # DELETE /kategoris/1.json
  def destroy
    @kategori.destroy
    respond_to do |format|
      format.html { redirect_to kategoris_url, notice: 'Kategori was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kategori
      @kategori = Kategori.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kategori_params
      params.require(:kategori).permit(:ad, :aciklama)
    end
end

app/helpers/kategoris_helper.rb
module KategorisHelper
end

app/views/kategoris/_form.html.erb
<%= form_with(model: kategori, local: true) do |form| %>
  <% if kategori.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kategori.errors.count, "error") %> prohibited this kategori from being saved:</h2>

      <ul>
      <% kategori.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ad %>
    <%= form.text_field :ad %>
  </div>

  <div class="field">
    <%= form.label :aciklama %>
    <%= form.text_area :aciklama %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kategoris/edit.html.erb
<h1>Editing Kategori</h1>

<%= render 'form', kategori: @kategori %>

<%= link_to 'Show', @kategori %> |
<%= link_to 'Back', kategoris_path %>

app/views/kategoris/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kategoris</h1>

<table>
  <thead>
    <tr>
      <th>Ad</th>
      <th>Aciklama</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kategoris.each do |kategori| %>
      <tr>
        <td><%= kategori.ad %></td>
        <td><%= kategori.aciklama %></td>
        <td><%= link_to 'Show', kategori %></td>
        <td><%= link_to 'Edit', edit_kategori_path(kategori) %></td>
        <td><%= link_to 'Destroy', kategori, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kategori', new_kategori_path %>

app/views/kategoris/new.html.erb
<h1>New Kategori</h1>

<%= render 'form', kategori: @kategori %>

<%= link_to 'Back', kategoris_path %>

app/views/kategoris/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ad:</strong>
  <%= @kategori.ad %>
</p>

<p>
  <strong>Aciklama:</strong>
  <%= @kategori.aciklama %>
</p>

<%= link_to 'Edit', edit_kategori_path(@kategori) %> |
<%= link_to 'Back', kategoris_path %>