config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :kategoris
  devise_for :authors
  root "blog/posts#index"
  
  namespace :authors do
     get '/account' => 'accounts#edit', as: :account
     put '/info' => 'accounts#update_info', as: :info 
     put '/change_password' => 'accounts#change_password', as: :change_password
     resources :posts do
         put 'publish' => 'posts#publish', on: :member
         put 'unpublish' => 'posts#unpublish', on: :member
     end
  end

  scope module: 'blog' do 
       get 'hakkimda' => 'pages#hakkimda', as: :hakkimda
       get 'iletisim' => 'pages#iletisim', as: :iletisim
       get 'posts' => 'posts#index', as: :posts
       get 'posts/:id' => 'posts#show', as: :post
  end
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb

			<!-- Nav -->
			
				<!-- Main Nav -->
				<div id="nav-fixed">
					<div class="container">
					    <p class="pull-right">	

<p class="navbar-text pull-right"> <% if user_signed_in? %> <strong><%= current_user.email %></strong><% else %> <%= link_to "Üye ol", new_user_registration_path, :class => 'navbar-link' %> | <%= link_to "Giriş Yap", new_user_session_path, :class => 'navbar-link' %> <% end %> </p>
                        <div class="nav-btns">
                            <% if user_signed_in? %>
							<button class="aside-btn"><i class="fa fa-bars"></i></button>
							<% end %>
						</div>
<%= link_to_unless_current "İngilizce", locale: "en" %>  |  
<%= link_to_unless_current "Türkçe", locale: "tr" %>
</p>
<div class="clear:both"></div>
						<!-- logo -->
						<div class="nav-logo">
						    <%= link_to   root_path, class: "#{yield(:blog_active)}" do  %>
								 <img src="http://tubitak.ozkanunsal.com/ruby/logo.png" alt="Neslihan Kolukısa" class="logo">
								 <% end %>
						</div>
						<!-- /logo -->

						<!-- nav -->
						<!-- nav -->
						<ul class="nav-menu nav">
							 <li class="cat-2"><%= link_to t('anasayfa'), root_path, class: "#{yield(:blog_active)}" %></li>
							<li  class="cat-1"> <%= link_to  t('hakkimda'), hakkimda_path, class: "#{yield(:hakkimda_active)}" %></li>
							<li  class="cat-3"> <%= link_to  "JavaScript", posts_path(tag: "JavaScript") %></li>
							<li  class="cat-4"> <%= link_to  "Css", posts_path(tag: "Css") %></li>
							<li  class="cat-1"> <%= link_to  "Jquery", posts_path(tag: "Jquery") %></li>
							<li  class="cat-2"><%= link_to t('iletisim'), iletisim_path, class: "nav-link #{yield(:iletisim_active)}" %></li>
						</ul>

						

						<!-- /nav -->

						<!-- search & aside toggle -->
							<!-- /nav -->

						<!-- search & aside toggle -->
						
						<!-- /search & aside toggle -->
					</div>
				</div><div style="clear:both"></div>
				<!-- /Main Nav -->
			<% if user_signed_in? %>
				<!-- Aside Nav -->
				<div id="nav-aside">
					<!-- nav -->
					<div class="section-row">
					    <%= current_user.email %>
						<ul class="nav-aside-menu">
						    	<li><%= link_to t('profil'), edit_user_registration_path, class:" #{yield(:author)}" %></li>
						    <% if  current_user.email== "neslihan.262@gmail.com" %>
							    <li><%= link_to t('gonderilerim'), authors_posts_path, class:" #{yield(:author)}" %></li>
							<% end %>

							<li><%= link_to t('cikis'), destroy_user_session_path, method: :delete %></li>
						</ul>
					</div>
					<!-- /nav -->

					<!-- widget posts -->

					<!-- /widget posts -->

					<!-- social links -->
				
					<!-- /social links -->

					<!-- aside nav close -->
					<!-- /aside nav close -->
				</div>
				<!-- Aside Nav -->
            <% end %>

			<!-- /Nav -->

   

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Neslihanın Blogu </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cloud.tinymce.com/5/tinymce.min.js"></script>
  </head>

  <body>
      
  	<%= render 'layouts/navbar' %>
    <!-- section -->
		<div class="section">
        <%= yield %>
    </div>
   <footer id="footer">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-5">
						<div class="footer-widget">
							<div class="footer-logo">
								 <%= link_to   root_path, class: "#{yield(:blog_active)}" do  %>
								 <img src="http://tubitak.ozkanunsal.com/ruby/logo.png" alt="">
								 <% end %>
							</div>
							<ul class="footer-nav">
								<li><a href="#">Neslihan Kolukısa</a></li>
								<li><a href="#"><%= t('kisisel') %></a></li>
							</ul>
							<div class="footer-copyright">
								<span>&copy; <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> 
							</div>
						</div>
					</div>

					<div class="col-md-4">
						<div class="row">
							<div class="col-md-6">
								<div class="footer-widget">
									<h3 class="footer-title"><%= t('hakkimda') %></h3>
									<ul class="footer-links">
										<li><%= link_to  t('hakkimda'), hakkimda_path, class: "#{yield(:hakkimda_active)}" %></li>
										<li><%= link_to t('iletisim'), iletisim_path, class: "#{yield(:iletisim_active)}" %></li>
									</ul>
								</div>
							</div>
							
						</div>
					</div>

					<div class="col-md-3">
						<div class="footer-widget">
							<h3 class="footer-title"><%= t('takip') %></h3>

							<ul class="footer-social">
								<li><a target="_blank" href="https://www.facebook.com/profile.php?id=100001206050650"><i class="fa fa-facebook"></i></a></li>
								<li><a target="_blank" href="https://twitter.com/neslihan_sftwre"><i class="fa fa-twitter"></i></a></li>
								<li><a target="_blank" href="https://aboutme.google.com/u/0/?referer=gplus"><i class="fa fa-google-plus"></i></a></li>
								<li><a target="_blank" href="http://www.linkedin.com/in/neslihankolukisa"><i class="fa fa-linkedin"></i></a></li>
							</ul>
						</div>
					</div>

				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</footer>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Neslihanın Blogu </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header id="header">
			<!-- Nav -->
			<div id="nav">
				<!-- Main Nav -->
				<div id="nav-fixed">
					<div class="container">
						<!-- logo -->
						<div class="nav-logo">
							<a href="" class="logo"><img src="http://tubitak.ozkanunsal.com/ruby/logo.png" alt=""></a>
						</div>
						<!-- /logo -->

						<!-- nav -->
					    <%= render 'layouts/navbar' %>
						<!-- /nav -->

						<!-- search & aside toggle -->
						<div class="nav-btns">
							<button class="aside-btn"><i class="fa fa-bars"></i></button>
							<button class="search-btn"><i class="fa fa-search"></i></button>
							<div class="search-form">
								<input class="search-input" type="text" name="search" placeholder="Enter Your Search ...">
								<button class="search-close"><i class="fa fa-times"></i></button>
							</div>
						</div>
						<!-- /search & aside toggle -->
					</div>
				</div>
				<!-- /Main Nav -->

				<!-- Aside Nav -->
				<div id="nav-aside">
					<!-- nav -->
					<div class="section-row">
						<ul class="nav-aside-menu">
							<li><a href="index.html">Home</a></li>
							<li><a href="about.html">About Us</a></li>
							<li><a href="#">Join Us</a></li>
							<li><a href="#">Advertisement</a></li>
							<li><a href="contact.html">Contacts</a></li>
						</ul>
					</div>
					<!-- /nav -->

					<!-- widget posts -->
					<div class="section-row">
						<h3>Recent Posts</h3>
						<div class="post post-widget">
							<a class="post-img" href="blog-post.html"><img src="" alt=""></a>
							<div class="post-body">
								<h3 class="post-title"><a href="blog-post.html">Pagedraw UI Builder Turns Your Website Design Mockup Into Code Automatically</a></h3>
							</div>
						</div>

						<div class="post post-widget">
							<a class="post-img" href="blog-post.html"><img src="" alt=""></a>
							<div class="post-body">
								<h3 class="post-title"><a href="blog-post.html">Why Node.js Is The Coolest Kid On The Backend Development Block!</a></h3>
							</div>
						</div>

						<div class="post post-widget">
							<a class="post-img" href="blog-post.html"><img src="" alt=""></a>
							<div class="post-body">
								<h3 class="post-title"><a href="blog-post.html">Tell-A-Tool: Guide To Web Design And Development Tools</a></h3>
							</div>
						</div>
					</div>
					<!-- /widget posts -->

					<!-- social links -->
					<div class="section-row">
						<h3>Follow us</h3>
						<ul class="nav-aside-social">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
						</ul>
					</div>
					<!-- /social links -->

					<!-- aside nav close -->
					<button class="nav-aside-close"><i class="fa fa-times"></i></button>
					<!-- /aside nav close -->
				</div>
				<!-- Aside Nav -->
			</div>
			<!-- /Nav -->
		</header>
    <!-- section -->
		<div class="section">
        <%= yield %>
    </div>
    
    
    
   <footer id="footer">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-5">
						<div class="footer-widget">
							<div class="footer-logo">
								<a href="index.html" class="logo"><img src="http://tubitak.ozkanunsal.com/ruby/logo.png" alt=""></a>
							</div>
							<ul class="footer-nav">
								<li><a href="#">Privacy Policy</a></li>
								<li><a href="#">Advertisement</a></li>
							</ul>
							<div class="footer-copyright">
								<span>&copy; <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></span>
							</div>
						</div>
					</div>

					<div class="col-md-4">
						<div class="row">
							<div class="col-md-6">
								<div class="footer-widget">
									<h3 class="footer-title">About Us</h3>
									<ul class="footer-links">
										<li><a href="about.html">About Us</a></li>
										<li><a href="#">Join Us</a></li>
										<li><a href="contact.html">Contacts</a></li>
									</ul>
								</div>
							</div>
							<div class="col-md-6">
								<div class="footer-widget">
									<h3 class="footer-title">Catagories</h3>
									<ul class="footer-links">
										<li><a href="category.html">Web Design</a></li>
										<li><a href="category.html">JavaScript</a></li>
										<li><a href="category.html">Css</a></li>
										<li><a href="category.html">Jquery</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>

					<div class="col-md-3">
						<div class="footer-widget">
							<h3 class="footer-title">Join our Newsletter</h3>
							<div class="footer-newsletter">
								<form>
									<input class="input" type="email" name="newsletter" placeholder="Enter your email">
									<button class="newsletter-btn"><i class="fa fa-paper-plane"></i></button>
								</form>
							</div>
							<ul class="footer-social">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
								<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
							</ul>
						</div>
					</div>

				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</footer>
  </body>
</html>